version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=iqraa_db
      - POSTGRES_USER=iqraa_user
      - POSTGRES_PASSWORD=iqraa_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=iqraa_db
      - POSTGRES_USER=iqraa_user
      - POSTGRES_PASSWORD=iqraa_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 